name: microc2tracks
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - fastp
  - bwa-mem2
  - samtools
  - htslib
  - pairtools
  - pairix
  - cooler
  - bioframe
  - multiqc
  - openjdk
  - pandas
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pip
